Discord Bot Token:
  token: ''
Discord Bot Prefix:
  botprefix: ''
Minecraft Text Channel ID (Leave blank to disable):
  textchannel: ''
Minecraft Admin Channel ID (Leave blank to disable):
  adminchannel: ''
Minecraft Text Channel Guild ID (Leave blank if you're not using the server link):
  mcguild: ''
